### ISSUE TITLE
[bug] leafer-editor 在选中元素的情况下销毁报错

### ISSUE THREAD

**Issue by Ronbb** [leaferjs/leafer-ui#239]
重现过程：

1. 创建`app`，创建`Rect`
2. 选中元素`Rect`
3. 销毁`app`
4. 出现报错

异常堆栈：

```
hook.js:608 Leafer TypeError: Cannot read properties of null (reading 'editBox')
    at get editBox (editor.esm.js:1842:40)
    at EditTool2.unload (editor.esm.js:1948:14)
    at Editor.updateEditTool (editor.esm.js:1531:18)
    at onTarget (editor.esm.js:1297:16)
    at Editor.set [as target] (editor.esm.js:296:47)
    at Editor.destroy (editor.esm.js:1824:18)
    at core.esm.js:5756:27
    at Array.forEach (<anonymous>)
    at Leafer2.removeAll (core.esm.js:5753:22)
    at Leafer2.destroy (core.esm.js:5645:22) Error
    at _Debug.error (core.esm.js:1358:19)
    at doDestory (draw.esm.js:1217:27)
```

可能的原因：

`this.editTool` 已经在 `Editor.destroy` 销毁 `this.editToolList` 时被销毁，但是 `this.editTool` 没有被修改为 `null`。

```typescript
   // /packages/editor/src/Editor.ts#L136
   public updateEditTool(): void {
        const tool = this.editTool
        if (tool) {
            this.editBox.unload()
            tool.unload()
            this.editTool = null
        }

        if (this.editing) {
            const tag = this.single ? this.list[0].editOuter as string : 'EditTool'
            this.editTool = this.editToolList[tag] = this.editToolList[tag] || EditToolCreator.get(tag, this)
            this.editBox.load()
            this.editTool.load()
        }
    }
```

**Comment by Ronbb** [comment]
临时解决方案：

```typescript
  useEffect(() => {
    if ((!app.current || app.current.destroyed) && container.current) {
      const newApp = new App({
        view: container.current,
        editor: {},
      });

      app.current = newApp;
    }

    return () => {
      delete app.current?.editor.editTool; // <- 提前删除
      app.current?.destroy(true);
      app.current = null;
    };
  }, []);

```

**Comment by leaferjs** [comment]
感谢反馈～，v1.0.6修复过一个类似的bug，你使用的版本是之前的还是最新的？

**Comment by Ronbb** [comment]
> 感谢反馈～，v1.0.6修复过一个类似的bug，你使用的版本是之前的还是最新的？

@leaferjs 目前使用的是 `leafer-editor": "^1.0.7`

**Comment by leaferjs** [comment]
好的，我下个版本修复一下～

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by leaferjs** [comment]
已修复，等新版发布～
